# Generated by Django 5.2.17 on 2026-10-02 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Under Construction', 'Under Construction'), ('Operational', 'Operational'), ('Completed', 'Completed')], default='Under Construction', max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('featured_image_url', models.URLField(blank=True)),
                ('image_caption', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('image_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=500)),
                ('column', models.CharField(choices=[('left', 'Left Column'), ('right', 'Right Column')], default='left', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='projects.project')),
            ],
            options={
                'ordering': ['column', 'order'],
            },
        ),
    ]
