# Generated by Django 5.2.17 on 2026-10-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('department', models.CharField(choices=[('General Inquiries', 'General Inquiries'), ('Investor Relations', 'Investor Relations & Shares'), ('Media & Press', 'Media & Press Communications'), ('Local Community & CSR', 'Local Community & Solukhumbu CSR'), ('Tenders & Procurement', 'Procurement & Tenders'), ('Careers', 'Careers & Engineering Internships')], default='General Inquiries', max_length=100)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='New', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
