# Generated by Django 5.2.17 on 2026-10-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutcompany_boardmember_companymilestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='project_site',
            field=models.CharField(default='Khumbu-Pasang Lhamu Rural Municipality, Solukhumbu District, Nepal', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registered_office',
            field=models.CharField(default='Madhyapur Thimi Municipality, Ward No. 3, Bhaktapur, Nepal', max_length=255),
        ),
    ]
